routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

// List of equipments for student
Route::get('student/equipments/', 'App\Http\Controllers\StudentEquipmentController@index');
Route::post('student/equipments/', 'App\Http\Controllers\StudentEquipmentController@filter');

// List of equipments for assistant
Route::get('assistant/equipments', 'App\Http\Controllers\AssistantEquipmentController@index');
Route::post('assistant/equipments', 'App\Http\Controllers\AssistantEquipmentController@filter');

// Delete equipment
Route::get('assistant/equipments/delete/{id}', 'App\Http\Controllers\AssistantEquipmentController@delete');

// Edit equipment
Route::get('assistant/equipments/edit/{id}', 'App\Http\Controllers\AssistantEquipmentController@edit');
Route::post('assistant/equipments/edit/', 'App\Http\Controllers\AssistantEquipmentController@editStore');

// Add new equipment
Route::get('assistant/equipments/create', 'App\Http\Controllers\AssistantEquipmentController@create');
Route::post('assistant/equipments/create', 'App\Http\Controllers\AssistantEquipmentController@store');

// Raport
Route::get('assistant/equipments/raport', 'App\Http\Controllers\AssistantEquipmentController@raport');

// List of tags
Route::get('assistant/tags/', 'App\Http\Controllers\TagController@index');

// Delete tag
Route::get('assistant/tags/delete/{id}', 'App\Http\Controllers\TagController@delete');

// Edit tag
Route::get('assistant/tags/edit/{id}', 'App\Http\Controllers\TagController@edit');
Route::post('assistant/tags/edit/', 'App\Http\Controllers\TagController@editStore');

// Add new tag
Route::get('assistant/tags/create', 'App\Http\Controllers\TagController@create');
Route::post('assistant/tags/create', 'App\Http\Controllers\TagController@store');


// List of all students
Route::get('assistant/students/', 'App\Http\Controllers\StudentController@index');

// Delete student
Route::get('assistant/students/delete/{id}', 'App\Http\Controllers\StudentController@delete');

// Edit student
Route::get('assistant/students/edit/{id}', 'App\Http\Controllers\StudentController@edit');
Route::post('assistant/students/edit/', 'App\Http\Controllers\StudentController@editStore');

// Add new student
Route::get('assistant/students/create', 'App\Http\Controllers\StudentController@create');
Route::post('assistant/students/create', 'App\Http\Controllers\StudentController@store');

////////////////////////////////////////////////////////////

// List of all users
Route::get('assistant/users/', 'App\Http\Controllers\UserController@index');

// Delete student
Route::get('assistant/users/deleteStudent/{id}', 'App\Http\Controllers\UserController@deleteStudent');

// Edit student
Route::get('assistant/users/editStudent/{id}', 'App\Http\Controllers\UserController@editStudent');
Route::post('assistant/users/editStudent', 'App\Http\Controllers\UserController@editStudentStore');

// Add new student
Route::get('assistant/users/createstudent', 'App\Http\Controllers\UserController@createStudent');
Route::post('assistant/users/createstudent', 'App\Http\Controllers\UserController@storeStudent');

// Add new assistant
Route::get('assistant/users/createassistant', 'App\Http\Controllers\UserController@createAssistant');
Route::post('assistant/users/createassistant', 'App\Http\Controllers\UserController@storeAssistant');

//////////////////////////

// List of all users
Route::get('assistant/checkouts/', 'App\Http\Controllers\CheckoutController@index');

Route::get('assistant/checkouts/student/{id}', 'App\Http\Controllers\CheckoutController@studentCheckouts');

Route::get('assistant/checkouts/new/{id}', 'App\Http\Controllers\CheckoutController@newCheckout');
Route::post('assistant/checkouts/new', 'App\Http\Controllers\CheckoutController@store');

Route::get('assistant/checkouts/remove/{id}', 'App\Http\Controllers\CheckoutController@remove');

Route::get('auth/passwords/reset', 'App\Http\Controllers\Auth\ResetPasswordController@index');
Route::post('auth/passwords/reset', 'App\Http\Controllers\Auth\ResetPasswordController@update');

app/Models/Equipment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use DB;

class Equipment extends Model
{
    use HasFactory;

    public $timestamps = false;

    protected $fillable = [
        'name',
        'model',
        'picture_path',
        'description',
        'producent_url'
    ];

    protected $hidden = [
        'id'
    ];

    protected $table = 'equipments';

    public function tags(){
        return $this->belongsToMany(Tag::class, 'equipments_tags');
    }

    public function getTagsIdsAttribute(){
        $tags = $this->tags()->get();

        $tagsIds = array();
        
        foreach ($tags as $tag) {

            array_push($tagsIds, $tag->id);
        }

        return $tagsIds;
    }

    public function pieces(){
        return $this->hasMany(EquipmentPiece::class, 'equipment_id');
    }

    public function getQuantityAttribute(){

        return $this->pieces()->count();
    }

    public function getAvailableQuantityAttribute(){

        $pieces = $this->pieces()->get();

        $available = $this->quantity;

        foreach($pieces as $piece){
            
            $available = $available - $piece->checkouts->count();
        }

        return $available;
    }
}

app/Models/EquipmentPiece.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

use App\Models\Checkout;
use App\Models\Equipment;

class EquipmentPiece extends Model
{
    use HasFactory;

    public $timestamps = false;

    protected $fillable = [
        'number',
        'equipment_id'
    ];

    public function checkouts(){
        return $this->hasMany(Checkout::class, 'equipment_piece_id');
    }

    public function checkout(){
        return $this->hasOne(Checkout::class, 'equipment_piece_id')->latest();
    }

    public function equipment(){
        return $this->belongsTo(Equipment::class, 'equipment_id');
    }

    public function getCheckoutsQuantityAttribute(){

        return $this->checkouts()->count();
    }
}

resources/views/assistant/equipments/create.blade.php
@extends('layouts.template')
@section('content')


<div class="container">
    <h2>Tworzenie nowego elementu wyposażenia:</h2>

    <form action="{{ action('App\Http\Controllers\AssistantEquipmentController@store') }}" method="POST" role="form" enctype="multipart/form-data">
        <input type="hidden" name="_token" value="{{ csrf_token() }}"/>

        <div class="form-group">
            <label for="name">Nazwa</label>
            <input type="text" class="form-control" name="equipmentName"/>
        </div>

        <div class="form-group">
            <label for="model">Model</label>
            <input type="text" class="form-control" name="model"/>
        </div>

        <div class="form-group">
            <label for="description">Opis</label>
            <input type="text" class="form-control" name="description"/>
        </div>

        <div class="form-group">
            <label for="producent_url">Producent</label>
            <input type="text" class="form-control" name="producent_url"/>
        </div>

        <div class="form-group">
            <label for="image">Fotografia</label>
            <input type="file" class="form-control" name="image"/>
        </div>
        
        <div class="form-group">
            <label for="tags[]">Tagi:</label>
            @foreach ($allTags as $tag)
            <div class="row m-1">
                <input class="form-check-input form-control" type="checkbox" name="tags[]" value="{{$tag->id}}" aria-label="..."/>
                &nbsp; {{$tag->name}}
            </div>
            @endforeach
        </div>

        <div class="form-group">
            <label for="quantity">Ilość</label>
            <input type="text" class="form-control" name="quantity"/>
        </div>
        </br>

        <input type="submit" value="Zapisz" class="btn btn-primary"/>

    </form>
</div>


@endsection('content')
    

resources/views/assistant/equipments/edit.blade.php
@extends('layouts.template')

@section('content')


<div class="container">
    <h2>Edycja {{$equipment->name}}</h2>

    <form action="{{ action('App\Http\Controllers\AssistantEquipmentController@editStore') }}" method="POST" role="form" enctype="multipart/form-data">
        <input type="hidden" name="_token" value="{{ csrf_token() }}"/>
        <input type="hidden" name="id" value="{{ $equipment->id }}"/>

        <div class="form-group">
            <label for="name">Nazwa</label>
            <input type="text" class="form-control" name="equipmentName" value="{{$equipment->name}}"/>
        </div>

        <div class="form-group">
            <label for="name">Model</label>
            <input type="text" class="form-control" name="model" value="{{$equipment->model}}"/>
        </div>

        <div class="form-group">
            <label for="name">Opis</label>
            <input type="text" class="form-control" name="description" value="{{$equipment->description}}"/>
        </div>

        <div class="form-group">
            <label for="name">Producent</label>
            <input type="text" class="form-control" name="producent_url" value="{{$equipment->producent_url}}"/>
        </div>

        <div class="form-group">
            <label for="image">Fotografia</label>
            <input type="file" class="form-control" name="image" value="{{$equipment->picture_path}}"/>
        </div>
        <br>

        <div class="form-group">
            <label for="name">Tagi:</label>
            @foreach ($allTags as $tag)
            <div class="row m-1">
                <input class="form-check-input form-control" type="checkbox" name="tags[]" value="{{$tag->id}}" <?php if(in_array($tag->id, $equipment->tagsIds)) echo "checked='checked'"; ?> aria-label="..."/>
                &nbsp; {{$tag->name}}
            </div>
            @endforeach
        </div>
        </br>

        <input type="submit" value="Zapisz" class="btn btn-primary"/>

    </form>
</div>


@endsection('content')
    

resources/views/assistant/equipments/list.blade.php
@extends('layouts.template')

@section('content')

<div class="sidebar">
    <form action="{{ action('App\Http\Controllers\AssistantEquipmentController@filter')}}" method="POST" role="form">
        <input type="hidden" name="_token" value="{{ csrf_token() }}"/> 
        @foreach ($allTags as $tag)
        <div class="row">
            <input class="form-check-input me-1 form-control" type="checkbox" name="selectedTags[]" value="{{$tag->id}}" aria-label="..." <?php if(in_array($tag->id, $selectedTagsIds)) echo "checked='checked'"; ?> />
            {{$tag->name}}
        </div>
        @endforeach
        <input type="submit" value="Filtruj" class="btn btn-primary"/>
    </form>   

</div>

<div class="main">
    <div class="container">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Fotografia</th>
                    <th scope="col">Nazwa</th>
                    <th scope="col">Model</th>
                    <th scope="col">Opis</th>
                    <th scope="col">Producent</th>
                    <th scope="col">Ilość</th>
                    <th scope="col">Dostępne</th>
                    <th scope="col">Tagi</th>
                    <th scope="col">Operacje</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($equipmentsList as $equipment)
                    <tr>
                        <td><img src="{{asset($equipment->picture_path) }}" height="100px" width="100px" alt="" title=""/></td>
                        <td>{{$equipment->name}}</td>
                        <td>{{$equipment->model}}</td>
                        <td>{{$equipment->description}}</td>
                        <td><a href="{{$equipment->producent_url}}">{{$equipment->producent_url}}</td>
                        <td>{{$equipment->quantity}}</td>
                        <td>{{$equipment->available_quantity}}</td>
                        <td>
                            @foreach ($equipment->tags as $tag)
                                <form method="post" action="{{ action('App\Http\Controllers\AssistantEquipmentController@filter')}}" class="inline">
                                    <input type="hidden" name="_token" value="{{ csrf_token() }}"/>
                                    <input type="hidden" name="selectedTags[]" value="{{$tag->id}}"/>
                                    <input type="submit" class="btn btn-outline-secondary btn-sm m-1" value="{{$tag->name}}"/>
                                </form>
                            @endforeach
                        </td>
                        <td>
                            <div class="btn-group-vertical">
                                <a type="button" class="btn btn-success m-1 btn-sm" href="{{ URL::to('assistant/equipments/edit/' . $equipment->id) }}">Edytuj</a>
                                <a type="button" class="btn btn-danger m-1 btn-sm" href="{{ URL::to('assistant/equipments/delete/' . $equipment->id) }}">Usuń</a>
                            </div>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>

        <a class="btn btn-outline-secondary" href="{{ URL::to('assistant\equipments\create') }}">Dodaj nowy element wyposażenia</a>
    </div>
</div>



@endsection('content')
    

resources/views/assistant/equipments/raport.blade.php
@extends('layouts.template')

@section('content')

<div class="main">
    <div class="container">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Nazwa</th>
                    <th scope="col">Model</th>
                    <th scope="col">Numer</th>
                    <th scope="col">Status</th>
                    <th scope="col">Student</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($equipmentsList as $equipment)
                    <tr>
                        <td>{{$equipment->name}}</td>
                        <td>{{$equipment->model}}</td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                    @foreach ($equipment->pieces as $piece)
                        @if ($piece->checkouts_quantity == 0)
                            <tr>
                                <td></td>
                                <td></td>
                                <td>{{$piece->number}}</td>
                                <td>Dostępny</td>
                                <td></td>
                            </tr>
                        @else
                            <tr>
                                <td></td>
                                <td></td>
                                <td>{{$piece->number}}</td>
                                <td>Wypożyczony</td>
                                <td>{{$piece->checkout->student->first_name}} {{$piece->checkout->student->last_name}} - {{$piece->checkout->student->email}}</td>
                            </tr>
                        @endif

                    @endforeach
                @endforeach
            </tbody>
        </table>
    </div>
</div>



@endsection('content')